---
# Domain
forgejo_server_domain: forgejo.hackandpwned.fr

# Security

forgejo_security_install_lock: True

forgejo_server_ssh_domain: "{{ ansible_default_ipv4.address }}"

forgejo_admin_username: "jphetphoumy"
forgejo_admin_email: "jphetphoumy@hackandpwned.fr"
forgejo_admin_password: "admin"
