restic_repo_password: ENC[AES256_GCM,data:tKLyRzBt,iv:9XvkZYgqxUYk2DiY6H1jVB6NsZapRcP2Ak9lE5NdJUQ=,tag:MJ5KnmG/IMVGgOck9dEtzw==,type:str]
restic_backups:
    - name: VST_Backup
      user: reaper-backup
      repository: /mnt/backup/VST_Backup
    - name: DRUMKIT_AND_SAMPLE
      user: reaper-backup
      repository: /mnt/backup/DRUMKIT_AND_SAMPLE
    - name: ReaperBackup
      user: reaper-backup
      repository: /mnt/backup/ReaperBackup
    - name: MusicBackup
      user: reaper-backup
      repository: /mnt/backup/MusicBackup
sops:
    age:
        - recipient: age1survjknrlvvxq9lnjq0uu0v9ugyeezjcf6kdsm7jmxa4rmx4ucps5arhrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSGpsUkIzUUIreXZ1Wlc4
            MGtMOUNuc1k4WHFKWEdXSXNFTmREY2pMcjI4CjRyOU1JZE9valB4UWEwVzNQSm83
            dkVQYkFRSDJyOEQwblBZOE1hTk1sSzAKLS0tIHpBZk96ZGphL2pWaVpEb3RoNWdC
            SWJNQTJVdU15aUxGTmJHVkRDNzVwa1EK2tu9zfm4bILCrTfaJRCieFAigHXN/aMX
            qB3tpfFkzdLhsB06+A0QnSGC8RG4+X1uEOee6srmx2nQDGMok3QDOA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1txgjac6zr3m2429nryyyr95xpw0u6hnl29z0yadhh6u2cdx0f9ns3rg9jy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WjJNREZMVlR3QUljNUto
            bTU3dnRrOHhKand0U2MrcGZCdC93NkV1a3prCjFzVkk4Y3k4Vit5NGc4N0QySHA5
            cUlRV1ZXVnJ5dGE0NW15Qk82UmdFZ3cKLS0tIFRReC85djgweGZsaytNSEhmaFBC
            K3Q3TWJkZTlyOGM1Yzl0eDAyckFuNG8KH6SGgHUzrtoGObMrx0hWU/t8hUxOJgn5
            HhG4M9BUOoxctcSHBE1geH9nb4bEH3zHAn+7XnXu5nLMcnbDQle55g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-15T22:02:19Z"
    mac: ENC[AES256_GCM,data:hUpxDCanLHjNFbxLBA9YSk2ZOAUGkuVZ4tqoK7fhlU/GOUM4FdexBI0abYin2P8pI2odYb6RlYpKmBZs33XwGZcKHy8ShdzVHPPfq1UzmGmJA0Ac+lW3sZakdQAbULzyjs8oNm+M813dgvfw89iCJ/UTnhkOMD67N02IduNUFFg=,iv:yDYMJbKwA8fbp9fzRcIkHX1OQiAzx4vmIf8KDja1wCw=,tag:YWCgV6WbWn3hI17egJqzRA==,type:str]
    encrypted_regex: ^(.*_password)
    version: 3.10.2
